------------------
-- TABLAS --
------------------

CREATE TABLE TIPU (
   ID_TIPU INT AUTO_INCREMENT PRIMARY KEY,
   NOM VARCHAR (20) NOT NULL
);


CREATE TABLE TECNIC (
   ID_TECNIC INT AUTO_INCREMENT PRIMARY KEY,
   NOM VARCHAR (20) NOT NULL
);


CREATE TABLE DEPARTAMENT (
   ID_DEPARTAMENT INT AUTO_INCREMENT PRIMARY KEY,
   NOM VARCHAR(20) NOT NULL
);


CREATE TABLE INCIDENCIA (
   ID_INCIDENCIA INT AUTO_INCREMENT PRIMARY KEY,
   DATA_CREACIO DATETIME DEFAULT CURRENT_TIMESTAMP,
   DESCRIPCIO VARCHAR (200),
   DATA_INICI DATE,
   PRIORITAT ENUM ('ALTA','MITJANA','BAIXA'),
   ID_TIPU INT,
   ID_TECNIC INT,
   ID_DEPARTAMENT INT
);

CREATE TABLE ACTUACIO (
    ID_ACTUACIO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCIO VARCHAR (200),
    TEMPS_ACTUACIO INT,
    VISIBLE BOOLEAN,
    ESTAT ENUM ('PENDENT','ACABAT')
    ID_INCIDENCIA INT,
    ID_TECNIC
);


------------------
-- FOREIGN KEYS --
------------------


ALTER TABLE INCIDENCIA
   ADD CONSTRAINT FK_ID_TIPU FOREIGN KEY (ID_TIPU) REFERENCES TIPU (ID_TIPU) ON DELETE SET NULL;


ALTER TABLE INCIDENCIA
   ADD CONSTRAINT FK_ID_TECNIC FOREIGN KEY (ID_TECNIC) REFERENCES TECNIC (ID_TECNIC) ON DELETE SET NULL;


ALTER TABLE INCIDENCIA
   ADD CONSTRAINT FK_ID_DEPARTAMENT FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENT (ID_DEPARTAMENT) ON DELETE SET NULL;

ALTER TABLE ACTUACIO
    ADD CONSTRAINT FK_ID_INCIDENCIA FOREIGN KEY (ID_INCIDENCIA) REFERENCES INCIDENCIA (ID_INCIDENCIA) ON DELETE SET NULL;

ALTER TABLE ACTUACIO 
    ADD CONSTRAINT FK_ID_TECNIC FOREIGN KEY (ID_TECNIC) REFERENCES TECNIC (ID_TECNIC) ON DELETE SET NULL;

