SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS projecte_gip3
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'usuari'@'%' IDENTIFIED BY 'password_usuari';
GRANT ALL PRIVILEGES ON projecte_gip3.* TO 'usuari'@'%';
FLUSH PRIVILEGES;

USE projecte_gip3;

CREATE TABLE TIPU (
    ID_TIPU    INT          AUTO_INCREMENT PRIMARY KEY,
    NOM        VARCHAR(100) NOT NULL
);

CREATE TABLE TECNIC (
    ID_TECNIC  INT          AUTO_INCREMENT PRIMARY KEY,
    NOM        VARCHAR(100) NOT NULL
);

CREATE TABLE DEPARTAMENT (
    ID_DEPARTAMENT  INT          AUTO_INCREMENT PRIMARY KEY,
    NOM             VARCHAR(100) NOT NULL
);

CREATE TABLE INCIDENCIA (
    ID_INCIDENCIA   INT          AUTO_INCREMENT PRIMARY KEY,
    DATA_CREACIO    DATETIME     DEFAULT CURRENT_TIMESTAMP,
    DATA_INICI      DATE,
    DATA_FI         DATE,
    DESCRIPCIO      VARCHAR(500),
    PRIORITAT       ENUM('ALTA','MITJANA','BAIXA'),
    ESTAT           ENUM('OBERTA','EN_PROCES','TANCADA') DEFAULT 'OBERTA',
    ID_TIPU         INT,
    ID_TECNIC       INT,
    ID_DEPARTAMENT  INT
);

CREATE TABLE ACTUACIO (
    ID_ACTUACIO       INT          AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCIO        VARCHAR(500),
    TEMPS_ACTUACIO_MIN INT,
    VISIBLE           BOOLEAN      DEFAULT TRUE,
    ESTAT             ENUM('PENDENT','ACABAT') DEFAULT 'PENDENT',
    ID_INCIDENCIA     INT,
    ID_TECNIC         INT
);

ALTER TABLE INCIDENCIA
    ADD CONSTRAINT FK_INCIDENCIA_TIPU
    FOREIGN KEY (ID_TIPU) REFERENCES TIPU (ID_TIPU) ON DELETE SET NULL;

ALTER TABLE INCIDENCIA
    ADD CONSTRAINT FK_INCIDENCIA_TECNIC
    FOREIGN KEY (ID_TECNIC) REFERENCES TECNIC (ID_TECNIC) ON DELETE SET NULL;

ALTER TABLE INCIDENCIA
    ADD CONSTRAINT FK_INCIDENCIA_DEPARTAMENT
    FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENT (ID_DEPARTAMENT) ON DELETE SET NULL;

ALTER TABLE ACTUACIO
    ADD CONSTRAINT FK_ACTUACIO_INCIDENCIA
    FOREIGN KEY (ID_INCIDENCIA) REFERENCES INCIDENCIA (ID_INCIDENCIA) ON DELETE SET NULL;

ALTER TABLE ACTUACIO
    ADD CONSTRAINT FK_ACTUACIO_TECNIC
    FOREIGN KEY (ID_TECNIC) REFERENCES TECNIC (ID_TECNIC) ON DELETE SET NULL;

ALTER TABLE INCIDENCIA ADD COLUMN DEPARTAMENT VARCHAR(100);

INSERT INTO DEPARTAMENT (NOM) VALUES
('Informàtica'),
('Matemàtiques'),
('Història'),
('Biologia'),
('Física i Química'),
('Llengues');

INSERT INTO TECNIC (NOM) VALUES
('Pere Portas'),
('Joan Garcia'),
('Maria López'),

INSERT INTO TIPU (NOM) VALUES
('Problema de maquinari'),
('Problema de programari'),
('Problema de xarxa'),
('Problema de correu electrònic'),
('Problema de seguretat'),
('Problema impressora'),
('Problema de servidor'),
('Problema de base de dades'),
('Problema de còpia de seguretat'),
